import styled from 'styled-components'
import {
  space,
  width,
  color,
  display,
  maxWidth,
  minWidth,
  height,
  maxHeight,
  minHeight,
  size,
  alignItems,
  alignContent,
  justifyContent,
  flexWrap,
  flexBasis,
  flexDirection,
  flex,
  alignSelf,
  justifySelf,
  borders,
  borderColor,
  borderRadius,
  position,
  zIndex,
  top,
  right,
  bottom,
  left,
  textAlign,
} from 'styled-system'

const Box = styled('div')(
  {
    boxSizing: 'border-box',
  },
  space,
  width,
  color,
  display,
  maxWidth,
  minWidth,
  height,
  maxHeight,
  minHeight,
  size,
  alignItems,
  alignContent,
  justifyContent,
  flexWrap,
  flexBasis,
  flexDirection,
  flex,
  alignSelf,
  justifySelf,
  borders,
  borderColor,
  borderRadius,
  position,
  zIndex,
  top,
  right,
  bottom,
  left,
  textAlign,
)

Box.displayName = 'Box'
Box.propTypes = {
  ...space.propTypes,
  ...width.propTypes,
  ...color.propTypes,
  ...display.propTypes,
  ...maxWidth.propTypes,
  ...minWidth.propTypes,
  ...height.propTypes,
  ...maxHeight.propTypes,
  ...minHeight.propTypes,
  ...size.propTypes,
  ...alignItems.propTypes,
  ...alignContent.propTypes,
  ...justifyContent.propTypes,
  ...flexWrap.propTypes,
  ...flexBasis.propTypes,
  ...flexDirection.propTypes,
  ...flex.propTypes,
  ...alignSelf.propTypes,
  ...justifySelf.propTypes,
  ...borders.propTypes,
  ...borderColor.propTypes,
  ...borderRadius.propTypes,
  ...position.propTypes,
  ...zIndex.propTypes,
  ...top.propTypes,
  ...right.propTypes,
  ...bottom.propTypes,
  ...left.propTypes,
  ...textAlign.propTypes,
}

export default Box
